// Style Dictionary v4 config — generates both platforms' token files from
// tokens.json (the canonical source). Run from the repo root:
//   npx style-dictionary@4 build --config design-tokens/config.mjs
//
// Accepted token-level Propagate verdicts update tokens.json and re-run this
// build; the counterpart file changes mechanically (can't fail to compile).

const cap = (s) => s[0].toUpperCase() + s.slice(1);
const HEADER = "GENERATED by Style Dictionary from design-tokens/tokens.json — do not edit by hand.";

function swiftuiTheme({ dictionary }) {
  const colors = dictionary.allTokens.filter((t) => t.path[0] === "color");
  const numbers = dictionary.allTokens.filter((t) => t.path[0] !== "color");
  const colorLines = colors
    .map((t) => `    static let ${t.path[1]} = Color(hex: "${t.value}")`)
    .join("\n");
  const numberLines = numbers
    .map((t) => `    static let ${t.path[1]}: CGFloat = ${t.value}`)
    .join("\n");
  return `import SwiftUI

// ${HEADER}

extension Color {
    init(hex: String) {
        let v = UInt64(hex.dropFirst(), radix: 16) ?? 0
        self.init(
            red: Double((v >> 16) & 0xFF) / 255,
            green: Double((v >> 8) & 0xFF) / 255,
            blue: Double(v & 0xFF) / 255
        )
    }
}

enum Theme {
${colorLines}
${numberLines}
}
`;
}

function flutterTheme({ dictionary }) {
  const colors = dictionary.allTokens.filter((t) => t.path[0] === "color");
  const numbers = dictionary.allTokens.filter((t) => t.path[0] !== "color");
  const colorLines = colors
    .map((t) => `  static const Color ${t.path[1]} = Color(0xFF${t.value.slice(1).toUpperCase()});`)
    .join("\n");
  const numberLines = numbers
    .map((t) => `  static const double ${t.path[1]} = ${t.value};`)
    .join("\n");
  return `import 'package:flutter/material.dart';

// ${HEADER}

class AppTheme {
${colorLines}
${numberLines}
}
`;
}

function composeColors({ dictionary }) {
  const colors = dictionary.allTokens.filter((t) => t.path[0] === "color");
  const lines = colors
    .map((t) => `val ${cap(t.path[1])} = Color(0xFF${t.value.slice(1).toUpperCase()})`)
    .join("\n");
  return `package com.unitem.sample.ui.theme

import androidx.compose.ui.graphics.Color

// ${HEADER}

${lines}
`;
}

export default {
  source: ["design-tokens/tokens.json"],
  hooks: {
    formats: {
      "swiftui/theme": swiftuiTheme,
      "compose/theme-colors": composeColors,
      "flutter/theme": flutterTheme,
    },
  },
  platforms: {
    ios: {
      buildPath: "sample-ios/Sources/",
      files: [{ destination: "Theme.swift", format: "swiftui/theme" }],
    },
    android: {
      buildPath: "sample-android/app/src/main/java/com/unitem/sample/ui/theme/",
      files: [{ destination: "Color.kt", format: "compose/theme-colors" }],
    },
    flutter: {
      buildPath: "sample-flutter/lib/",
      files: [{ destination: "theme.dart", format: "flutter/theme" }],
    },
  },
};
