package com.unitem.sample.ui.theme

import androidx.compose.ui.graphics.Color

// GENERATED by Style Dictionary from design-tokens/tokens.json — do not edit by hand.

val BrandPrimary = Color(0xFF4F46E5)
val BrandInk = Color(0xFF1A1B4B)
val TextSecondary = Color(0xFF8A8BB3)
val Surface = Color(0xFFFFFFFF)
