import 'package:flutter/material.dart';

// GENERATED by Style Dictionary from design-tokens/tokens.json — do not edit by hand.

class AppTheme {
  static const Color brandPrimary = Color(0xFF4F46E5);
  static const Color brandInk = Color(0xFF1A1B4B);
  static const Color textSecondary = Color(0xFF8A8BB3);
  static const Color surface = Color(0xFFFFFFFF);
  static const double inputHeight = 52;
  static const double radiusButton = 12;
  static const double spacingUnit = 8;
  static const double headingSize = 28;
  static const double bodySize = 17;
}
